# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamepad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamepad.proto',
  package='remote_gamepad',
  syntax='proto3',
  serialized_options=_b('\n\027com.jrmo.remote_gamepadB\022RemoteGamepadProtoP\001'),
  serialized_pb=_b('\n\rgamepad.proto\x12\x0eremote_gamepad\"\x1d\n\x08\x43lientID\x12\x11\n\tclient_id\x18\x01 \x01(\t\"%\n\rJoystickState\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"9\n\x0b\x42uttonState\x12\t\n\x01\x41\x18\x01 \x01(\x08\x12\t\n\x01\x42\x18\x02 \x01(\x08\x12\t\n\x01X\x18\x03 \x01(\x08\x12\t\n\x01Y\x18\x04 \x01(\x08\"\xce\x01\n\x0cGamepadState\x12\x30\n\tleftStick\x18\x01 \x01(\x0b\x32\x1d.remote_gamepad.JoystickState\x12\x31\n\nrightStick\x18\x02 \x01(\x0b\x32\x1d.remote_gamepad.JoystickState\x12,\n\x07\x62uttons\x18\x03 \x01(\x0b\x32\x1b.remote_gamepad.ButtonState\x12+\n\tclient_id\x18\x04 \x01(\x0b\x32\x18.remote_gamepad.ClientID\"\x07\n\x05\x45mpty2\xe4\x01\n\x07Gamepad\x12\x46\n\x11InitializeGamepad\x12\x15.remote_gamepad.Empty\x1a\x18.remote_gamepad.ClientID\"\x00\x12L\n\x10SendGamepadState\x12\x1c.remote_gamepad.GamepadState\x1a\x18.remote_gamepad.ClientID\"\x00\x12\x43\n\x0e\x44\x65stroyGamepad\x12\x18.remote_gamepad.ClientID\x1a\x15.remote_gamepad.Empty\"\x00\x42/\n\x17\x63om.jrmo.remote_gamepadB\x12RemoteGamepadProtoP\x01\x62\x06proto3')
)




_CLIENTID = _descriptor.Descriptor(
  name='ClientID',
  full_name='remote_gamepad.ClientID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='remote_gamepad.ClientID.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=62,
)


_JOYSTICKSTATE = _descriptor.Descriptor(
  name='JoystickState',
  full_name='remote_gamepad.JoystickState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='remote_gamepad.JoystickState.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='remote_gamepad.JoystickState.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=101,
)


_BUTTONSTATE = _descriptor.Descriptor(
  name='ButtonState',
  full_name='remote_gamepad.ButtonState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='A', full_name='remote_gamepad.ButtonState.A', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='B', full_name='remote_gamepad.ButtonState.B', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='X', full_name='remote_gamepad.ButtonState.X', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Y', full_name='remote_gamepad.ButtonState.Y', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=160,
)


_GAMEPADSTATE = _descriptor.Descriptor(
  name='GamepadState',
  full_name='remote_gamepad.GamepadState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftStick', full_name='remote_gamepad.GamepadState.leftStick', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightStick', full_name='remote_gamepad.GamepadState.rightStick', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='remote_gamepad.GamepadState.buttons', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='remote_gamepad.GamepadState.client_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=369,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='remote_gamepad.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=378,
)

_GAMEPADSTATE.fields_by_name['leftStick'].message_type = _JOYSTICKSTATE
_GAMEPADSTATE.fields_by_name['rightStick'].message_type = _JOYSTICKSTATE
_GAMEPADSTATE.fields_by_name['buttons'].message_type = _BUTTONSTATE
_GAMEPADSTATE.fields_by_name['client_id'].message_type = _CLIENTID
DESCRIPTOR.message_types_by_name['ClientID'] = _CLIENTID
DESCRIPTOR.message_types_by_name['JoystickState'] = _JOYSTICKSTATE
DESCRIPTOR.message_types_by_name['ButtonState'] = _BUTTONSTATE
DESCRIPTOR.message_types_by_name['GamepadState'] = _GAMEPADSTATE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientID = _reflection.GeneratedProtocolMessageType('ClientID', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTID,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:remote_gamepad.ClientID)
  })
_sym_db.RegisterMessage(ClientID)

JoystickState = _reflection.GeneratedProtocolMessageType('JoystickState', (_message.Message,), {
  'DESCRIPTOR' : _JOYSTICKSTATE,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:remote_gamepad.JoystickState)
  })
_sym_db.RegisterMessage(JoystickState)

ButtonState = _reflection.GeneratedProtocolMessageType('ButtonState', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONSTATE,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:remote_gamepad.ButtonState)
  })
_sym_db.RegisterMessage(ButtonState)

GamepadState = _reflection.GeneratedProtocolMessageType('GamepadState', (_message.Message,), {
  'DESCRIPTOR' : _GAMEPADSTATE,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:remote_gamepad.GamepadState)
  })
_sym_db.RegisterMessage(GamepadState)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'gamepad_pb2'
  # @@protoc_insertion_point(class_scope:remote_gamepad.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_GAMEPAD = _descriptor.ServiceDescriptor(
  name='Gamepad',
  full_name='remote_gamepad.Gamepad',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=381,
  serialized_end=609,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitializeGamepad',
    full_name='remote_gamepad.Gamepad.InitializeGamepad',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CLIENTID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendGamepadState',
    full_name='remote_gamepad.Gamepad.SendGamepadState',
    index=1,
    containing_service=None,
    input_type=_GAMEPADSTATE,
    output_type=_CLIENTID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DestroyGamepad',
    full_name='remote_gamepad.Gamepad.DestroyGamepad',
    index=2,
    containing_service=None,
    input_type=_CLIENTID,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMEPAD)

DESCRIPTOR.services_by_name['Gamepad'] = _GAMEPAD

# @@protoc_insertion_point(module_scope)
