# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gamepad_pb2 as gamepad__pb2


class GamepadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InitializeGamepad = channel.unary_unary(
        '/remote_gamepad.Gamepad/InitializeGamepad',
        request_serializer=gamepad__pb2.Empty.SerializeToString,
        response_deserializer=gamepad__pb2.ClientID.FromString,
        )
    self.SendGamepadState = channel.unary_unary(
        '/remote_gamepad.Gamepad/SendGamepadState',
        request_serializer=gamepad__pb2.GamepadState.SerializeToString,
        response_deserializer=gamepad__pb2.ClientID.FromString,
        )
    self.DestroyGamepad = channel.unary_unary(
        '/remote_gamepad.Gamepad/DestroyGamepad',
        request_serializer=gamepad__pb2.ClientID.SerializeToString,
        response_deserializer=gamepad__pb2.Empty.FromString,
        )


class GamepadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def InitializeGamepad(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendGamepadState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DestroyGamepad(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GamepadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InitializeGamepad': grpc.unary_unary_rpc_method_handler(
          servicer.InitializeGamepad,
          request_deserializer=gamepad__pb2.Empty.FromString,
          response_serializer=gamepad__pb2.ClientID.SerializeToString,
      ),
      'SendGamepadState': grpc.unary_unary_rpc_method_handler(
          servicer.SendGamepadState,
          request_deserializer=gamepad__pb2.GamepadState.FromString,
          response_serializer=gamepad__pb2.ClientID.SerializeToString,
      ),
      'DestroyGamepad': grpc.unary_unary_rpc_method_handler(
          servicer.DestroyGamepad,
          request_deserializer=gamepad__pb2.ClientID.FromString,
          response_serializer=gamepad__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'remote_gamepad.Gamepad', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
